name: forcedotcom/sf-fx-sdk-java/ci
on:
  push:
jobs:
  maven:
    runs-on: sfdc-hk-ubuntu-latest
    strategy:
      matrix:
        executor:
        - openjdk-8
        - openjdk-11
    steps:
    - uses: actions/checkout@v2
    - run: "./mvnw package"
